const uniqolor = require("uniqolor");

const genres = [
  { name: "Acoustic" },
  { name: "Afrobeat" },
  { name: "Alt-rock" },
  { name: "Alternative" },
  { name: "Ambient" },
  { name: "Anime" },
  { name: "Black-metal" },
  { name: "Bluegrass" },
  { name: "Blues" },
  { name: "Bossanova" },
  { name: "Brazil" },
  { name: "Breakbeat" },
  { name: "British" },
  { name: "Cantopop" },
  { name: "Chicago-house" },
  { name: "Children" },
  { name: "Chill" },
  { name: "Classical" },
  { name: "Club" },
  { name: "Comedy" },
  { name: "Country" },
  { name: "Dance" },
  { name: "Dancehall" },
  { name: "Death-metal" },
  { name: "Deep-house" },
  { name: "Detroit-techno" },
  { name: "Disco" },
  { name: "Disney" },
  { name: "Drum-and-bass" },
  { name: "Dub" },
  { name: "Dubstep" },
  { name: "Edm" },
  { name: "Electro" },
  { name: "Electronic" },
  { name: "Emo" },
  { name: "Folk" },
  { name: "Forro" },
  { name: "Funk" },
  { name: "Garage" },
  { name: "Gospel" },
  { name: "Goth" },
  { name: "Grindcore" },
  { name: "Groove" },
  { name: "Grunge" },
  { name: "Guitar" },
  { name: "Happy" },
  { name: "Hard-rock" },
  { name: "Hardcore" },
  { name: "Hardstyle" },
  { name: "Heavy-metal" },
  { name: "Hip-hop" },
  { name: "Holidays" },
  { name: "Honky-tonk" },
  { name: "House" },
  { name: "Idm" },
  { name: "Industrial" },
  { name: "J-dance" },
  { name: "J-idol" },
  { name: "J-pop" },
  { name: "J-rock" },
  { name: "Jazz" },
  { name: "K-pop" },
  { name: "Kids" },
  { name: "Latin" },
  { name: "Latino" },
  { name: "Malay" },
  { name: "Mandopop" },
  { name: "Metal" },
  { name: "Metal-misc" },
  { name: "Metalcore" },
  { name: "Minimal-techno" },
  { name: "Mpb" },
  { name: "Opera" },
  { name: "Pagode" },
  { name: "Party" },
  { name: "Piano" },
  { name: "Pop" },
  { name: "Post-dubstep" },
  { name: "Power-pop" },
  { name: "Progressive-house" },
  { name: "Psych-rock" },
  { name: "Punk" },
  { name: "Punk-rock" },
  { name: "R-n-b" },
  { name: "Rainy-day" },
  { name: "Reggae" },
  { name: "Reggaeton" },
  { name: "Road-trip" },
  { name: "Rock" },
  { name: "Rock-n-roll" },
  { name: "Rockabilly" },
  { name: "Romance" },
  { name: "Sad" },
  { name: "Salsa" },
  { name: "Samba" },
  { name: "Sertanejo" },
  { name: "Show-tunes" },
  { name: "Singer-songwriter" },
  { name: "Ska" },
  { name: "Sleep" },
  { name: "Songwriter" },
  { name: "Soul" },
  { name: "Soundtracks" },
  { name: "Spanish" },
  { name: "Study" },
  { name: "Summer" },
  { name: "Synth-pop" },
  { name: "Tango" },
  { name: "Techno" },
  { name: "Trance" },
  { name: "Trip-hop" },
  { name: "Work-out" },
  { name: "World-music" },
];

const generateGenres = () => {
  return genres.map((genre) => {
    const { color, isLight } = uniqolor(genre.name, { format: "rgb" });
    const rgbaColor = color.replace("rgb", "rgba");

    return {
      name: genre.name,
      color: rgbaColor.replace(")", ", 0.6)"),
      colorHover: rgbaColor.replace(")", ", 1)"),
      textColor: isLight ? "#000" : "#fff",
    };
  });
};

console.log(JSON.stringify(generateGenres()));
