name: Build and push Docker images on hub

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Setup Node.js and build the project from outside Docker container. HoloPlay is an client only app, so we don't need to build it for other platforms.
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm i
      - run: npm run build
      - name: Cache build folder
        id: cache-build
        uses: actions/cache/save@v3
        with:
          path: ${{ github.workspace }}/build
          key: ${{ github.sha }}-build

  docker-build-push:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      - uses: actions/cache/restore@v3
        id: restore-build
        with:
          path: ${{ github.workspace }}/build
          key: ${{ github.sha }}-build
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: spout8301/holoplay:latest,spout8301/holoplay:${{ steps.package-version.outputs.current-version }}
